LAB SESSION 1

1. array creation and manipulation with numpy

In [87]:
# LAB SESSION 1

import numpy as np

In [88]:
arr1 = np.arange(10)
print(arr1)
print(arr1.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [89]:
# ARRAY MANIPULATION

arr1 = np.array([0,6,2])
print('arr1 type:', type(arr1))
print('arr1 ARRAY TYPE:', arr1.shape)

arr1 type: <class 'numpy.ndarray'>
arr1 ARRAY TYPE: (3,)


In [90]:
arr2 = np.array([[1,2]])
print(arr2.shape)

(1, 2)


In [91]:
arr3 = np.array([[[1,2]]])
print(arr3.shape)

(1, 1, 2)


In [92]:
arr4 = np.array([[1,2],
                 [2,3],
                 [3,4]])
print(arr4.shape)

(3, 2)


In [93]:
arr5 = np.array([[[1,2,3,4],
                  [2,3,4,5],
                  [2,3,4,5],
                  [5,4,3,2]]])
print(arr5.shape)

(1, 4, 4)


In [94]:
arr6 =np.array([[[1,2,4,5,3,2],[1,2,3,4,5,3],[1,2,3,4,5,6],
          [4,6,7,8,9,0],[6,8,6,5,4,7]],
        [[1,2,4,5,3,2],[1,2,3,4,5,3],[1,2,3,4,5,6],
         [4,6,7,8,9,0],[6,8,6,5,4,7]]])
print(arr6.shape)
#pred 2,6,5   u got it wrong, the real size is 2,5,6
#2 blocks, with 5 subarrays (the subarrays that contain 6 elemtnts) THUS (2,5,6)

         

(2, 5, 6)


In [95]:
# Creating an array with dimensions 2x6x5
arr = np.random.rand(2, 6, 5)
print(arr)
print("Array shape:", arr.shape)

[[[0.93519272 0.80078705 0.72222553 0.18285688 0.2730376 ]
  [0.81186499 0.8249471  0.8521628  0.69920934 0.64600315]
  [0.71205934 0.63859098 0.98894544 0.32151966 0.85390062]
  [0.25918716 0.47221336 0.02164217 0.16229466 0.64952715]
  [0.95546934 0.91165529 0.37281288 0.00864996 0.65431016]
  [0.83263162 0.68896017 0.25377149 0.69546126 0.56966038]]

 [[0.80897387 0.25184778 0.17250127 0.59297035 0.39001273]
  [0.80072848 0.2719969  0.26973172 0.64141314 0.11394555]
  [0.27401118 0.23218637 0.20314794 0.69164252 0.01568794]
  [0.47407198 0.81373389 0.73104716 0.35378328 0.168214  ]
  [0.34159543 0.50748851 0.94798904 0.47635106 0.13030162]
  [0.49373268 0.44456672 0.76841959 0.0855013  0.96382727]]]
Array shape: (2, 6, 5)


2. ndarray (N-dim array) data types

In [97]:
#numeric array
num_list = [1,2]
print(type(num_list))

num_arr = np.array(num_list)
print(type(num_arr))
print("This is a LIST!", num_list, "\n", "This is a numpy array!:", num_arr)

<class 'list'>
<class 'numpy.ndarray'>
This is a LIST! [1, 2] 
 This is a numpy array!: [1 2]


In [101]:
# an ndarray cannot have different types of value included
# how about when we mix int + str? (int < Str)
mix_list = [1,'haha']
mix_array = np.array(mix_list)
print(mix_list, type(mix_list), "\n")
print("In the following mixed array, the previous integers transform in Str" , mix_array, type(mix_array), 
      "\n from numpy.dtype class", mix_array.dtype)

[1, 'haha'] <class 'list'> 

In the following mixed array, the previous integers transform in Str ['1' 'haha'] <class 'numpy.ndarray'> 
 from numpy.dtype class <U11


3.creating NdARRAYS (arange,zero,one)

In [108]:
# arange orderly assing numeric starting from 0

sequence_arr = np.arange(5) # start at index 0 but start at 5
print(sequence_arr) # should get numbers from 0 to 4, remember indexing in python
print(sequence_arr.dtype, sequence_arr.shape) 

[0 1 2 3 4]
int32 (5,)


In [110]:
# filling with zeros
zero_arr = np.zeros((3,3))
print(zero_arr)
print( "Type:", zero_arr.dtype, "\n", "Shape:", zero_arr.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Type: float64 
 Shape: (3, 3)


In [122]:
# reshaping arrays
print("og array:", num_arr, "\n") #(1,2)
reshape_arr = num_arr.reshape(2,1)
print("new shaped arr: \n" ,reshape_arr) #compatible because 1x2 = 2 / 2x1 = 2

# does not work with lets say "reshape.(3,1)"
# insufficient numner of ndarrays

og array: [1 2] 

new shaped arr: 
 [[1]
 [2]]


In [139]:
# Utilizing -1 when reshaping
arr09 = np.arange(6)
print(arr09)
print("Previous shape:", arr09.shape) #shape is (6,)

# When we reshape & use -1 in either row or column position
# the number gets assigned automatically 
arr10 = arr09.reshape(-1,6)
print("new shape:", arr10.shape) # (1,6) 1x6=6
arr11 = arr09.reshape(6,-1)
print("new shape:", arr11.shape) # (6,1) 6x1=6
arr12 = arr09.reshape(-1,1)
print("new shape:", arr12.shape) 
# with (-1,1) we ask numpy to reshape array with a column & rows neccesary
# this to accomodate the data

[0 1 2 3 4 5]
Previous shape: (6,)
new shape: (1, 6)
new shape: (6, 1)
new shape: (6, 1)


In [143]:
# one more example of how it automatically assigns unumber

arr13 = np.random.rand(4,5) # this array has 4x5 = 20 elements
arr14 = arr13.reshape(-1,10) # should assign a 2 so 2x10 = 20 elements
arr15 = arr13.reshape(2,-1) # should assign a 10 so 2x10  = 20 elements
print("Array 14 shape:", arr14.shape)
print("Array 15 shape:", arr15.shape)

Array 14 shape: (2, 10)
Array 15 shape: (2, 10)


4. array indexing -
    we can use indices to retrieve specific elements of the array

In [160]:
#array from 1 to 4 using start and stop parameters
in_arr = np.arange(start=1, stop=5) #elements should be 1-4
print("array:", in_arr)

# calling out the second element
# index start at 0 array[1] = 2
call = in_arr[1]
print("Second element is:", call)

array: [1 2 3 4]
Second element is: 2


In [162]:
# we can use '-' to pull elements from the last indices
print("array:", in_arr)
last = in_arr[-1] # should be bringing 4 back
second_to_last = in_arr[-2] # should bring 3 back
print("last element:", last)
print("second to last element", second_to_last)

array: [1 2 3 4]
last element: 4
second to last element 3


In [164]:
# Replacing & Updating elements with indexing
print("array:", in_arr)
in_arr[0] = 0 # changing 1 to 0
in_arr[3] = 5 # changing 4 to 5
print("array:", in_arr)

array: [1 2 3 4]
array: [0 2 3 5]


In [166]:
# Sicling arrays with indexing
arr_2slice = np.arange(start=1,stop=10) #array w/elements 1 to 9
print(arr_2slice)
sliced_arr = arr_2slice[0:4] # should bring numbers 1-4,index starts at 0
print("sliced arr:", sliced_arr)

[1 2 3 4 5 6 7 8 9]
sliced arr: [1 2 3 4]


In [174]:
# Slicing indexing notation example
to_slice = np.arange(start=1,stop=11) #array w/elements 1 to 10

slice1= to_slice[4:] #selects index 4 to end of array so 4-10
slice2= to_slice[:6] #selects from beginning of array to index 8 so 1-8
slice3= to_slice[:] #selects all exisitng items

print("Before slice:", to_slice)
print("Index 5 to end:", slice1)
print("Beginning of array to index 6:", slice2)
print("End to end (all):", slice3)

Before slice: [ 1  2  3  4  5  6  7  8  9 10]
Index 5 to end: [ 5  6  7  8  9 10]
Beginning of array to index 6: [1 2 3 4 5 6]
End to end (all): [ 1  2  3  4  5  6  7  8  9 10]


In [176]:
# Fancy indexing / ADVANCED INDEXING
rand = np.random.RandomState(42) #setting random state

arr = rand.randint(100, size=10) #create random array numbers 1-10-, size 10
print(arr)


[51 92 14 71 60 20 82 86 74 74]


In [178]:
#Accessing different elements with Fancy indexing

#if i want the 3rd, the 5th and 9th number
[arr[2], arr[4], arr[8]]

[14, 60, 74]

In [180]:
# Passing a single list/array of indices for same result
indices = [0,2,5] # 1st, 3rd & 4th elements
arr[indices]

array([51, 14, 20])

In [182]:
# W/ fancy indexing the shape of result reflects shape of the index arrays
# rather than the shape of the array being indexed
ind = np.array([[1,2],
                [3,4]]) # 2nd through 5th elements
arr[ind]

array([[92, 14],
       [71, 60]])

In [198]:
# Fancy indexing & multiple dimensions
X = np.arange(12).reshape(4,3) #range of 1-12 & shape of 4x3
X

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [210]:
# Alike standard indexing, 1st index refers to the row
# 2nd to the column
row = np.array([0, 1, 2]) #gets 1st,2nd&3rd elements from rows 0,1,2
col = np.array([1, 1, 1]) #getting elements from second column of index 1
X[row,col] # creates a new array

array([1, 4, 7])

In [216]:
# REMEMBER that with FANCY/ADVANCED indexing
# return value refelcts broadcasted shape of indices
# rather than the shape of the array being indexed
#When using fancy (or advanced) indexing in NumPy,
#the way the output is shaped depends more on the shapes
#of the index arrays you're using, rather than the shape 
#of the original array you're indexing into.



In [218]:
# Boolean indexing
arr_1d = np.arange(start=1, stop=10)

# inside the list [] arr_id > 5 Boolean indexing
bool_arr = arr_1d[arr_1d > 5] # selecting elements true to have value over 5
print("Boolean indexing result:", bool_arr)

Boolean indexing result: [6 7 8 9]


In [222]:
# Comparing original array with the bigger than condition 
print("Original array:", arr_1d)
print("Boolean values:", arr_1d > 5) # selecting vals bigger than 5
# notice how indexes 6

Original array: [1 2 3 4 5 6 7 8 9]
Boolean values: [False False False False False  True  True  True  True]


NOTE: Advanced stuff involves Multi-D arrays & Indexing (bigger than the egs)

5. Other functions mentioned in lab module 1

- sort(), argsort() ~ this sorts data(hi to low, low to hi)
- np.dot() ~ gets result of multiplying matrix A & B
- transpose() ~ gets the inverse matrix

In [242]:
# example of transpose function
tobe_trans = np.array([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
after_trans = np.transpose(tobe_trans)
print("Original array: \n", tobe_trans, "\n")
print("Transposed array (inverted matrix): \n", after_trans)
print("Notice how the 2,3,6 swapped place with 4,7,8",
     "this replaces regular elements with their reciprocals in the matrix")

Original array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Transposed array (inverted matrix): 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Notice how the 2,3,6 swapped place with 4,7,8 this replaces regular elements with their reciprocals in the matrix
